name: "[Automated] build-contents action run by own desktop"

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  WOL:
    name: WOL
    runs-on: ubuntu-latest
    steps:
      - name: wake by magic-packet
        run: |
          echo "GitHub Server URL: $GITHUB_SERVER_URL"
          RESPONSE_HTTP_STATUS=$(curl -o /dev/null --connect-timeout 20 -H "Authorization: Basic ${{secrets.IPTIME_TOKEN}}" -w "%{http_code}" -X GET "${{secrets.IPTIME_DDNS}}:${{secrets.PORT_FOR_ACCESS}}/cgi-bin/wol_apply.cgi?act=wakeup&mac=${{secrets.IPTIME_MAC}}")
          if [ $RESPONSE_HTTP_STATUS -eq 200 ]; then
              echo 성공
          else
              echo 실패
          fi

  build:
    needs: [WOL]
    runs-on: self-hosted

    steps:
      - name: execute chmod permission
        run: |
          chmod 777 /home/jaeuk/actions-runner/_work/

      - name: Checkout source code # Repo checkout
        uses: actions/checkout@v4

      - name: Checkout node version
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Build Contents
        uses: ./.github/workflows/reusable_build_contents
        with:
          AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}

      - name: Commit Contents
        uses: ./.github/workflows/reusable_commit_contents
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  hibernate:
    needs: [WOL, build]
    runs-on: ubuntu-latest
    steps:
      - name: sleep by REST Server
        run: |
          echo "GitHub Server URL: $GITHUB_SERVER_URL"
          curl --version
          RESPONSE_HTTP_STATUS=$(curl -o /dev/null --connect-timeout 20 -w "%{http_code}" -X GET "${{secrets.IPTIME_DDNS}}:${{secrets.PORT_FOR_SLEEP}}/")
          if [ $RESPONSE_HTTP_STATUS -eq 200 ]; then
              echo 성공
          else
              echo 실패
          fi
