name: "[Automated] build-contents action run by own desktop"

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  WOL:
    name: WOL
    runs-on: ubuntu-latest
    steps:
        - name : wake by magic-packet
          run : |
              RESPONSE_HTTP_STATUS=$(curl -o /dev/null --connect-timeout 20 -H "Authorization: Basic ${{secrets.IPTIME_TOKEN}}" "${{secrets.IPTIME_DDNS}}/cgi-bin/wol_apply.cgi?act=wakeup&mac=${{secrets.IPTIME_MAC}}")
              echo 실패
              if [ $RESPONSE_HTTP_STATUS -eq 200 ]; then
                  echo 성공
              fi
              
  build:
    needs: [WOL]
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
